global using Xunit;
global using NSubstitute;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Google.Protobuf.WellKnownTypes;
global using Adaptor.Coordinator.Abstractions;
global using Adaptor.Coordinator.Configuration;
global using Adaptor.Coordinator.Services;
global using Adaptor.Service.Services;
